# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namepoll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selector',
            old_name='selectiongroups',
            new_name='selection_groups',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='lastchecked',
            new_name='last_checked',
        ),
    ]
