# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namepoll', '0002_auto_20170412_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('0', 'Yes'), ('2', 'No'), ('1', 'Maybe')], default='0', max_length=1),
        ),
    ]
