# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namepoll', '0004_auto_20170412_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='gender',
            field=models.CharField(choices=[('0', 'Girl'), ('1', 'Boy')], default='1', max_length=1),
        ),
    ]
